/*
 * Android File Transfer for macOS — public market comparison data
 * Research snapshot: 2026-07-22
 *
 * This file intentionally uses plain browser JavaScript so the comparison
 * explorer can run without a build step, analytics, remote data, or cookies.
 */
(function exposeMarketData() {
  "use strict";

  window.MARKET_RESEARCH = Object.freeze({
    schemaVersion: 1,
    title: "Android-to-Mac file transfer landscape",
    asOf: "2026-07-22",
    inventorySize: 45,
    releaseCompared: "Android File Transfer for macOS v@@VERSION@@",
    releaseUrl:
      "https://github.com/nostitos/android-file-transfer-for-macos/releases/latest",
    scope:
      "A dated inventory of direct file browsers plus representative ADB, nearby-sharing, phone-manager, OEM, sync, cloud, and built-in alternatives available to Mac users at the research date.",
    boundary:
      "No finite list can include every white-label App Store listing, generic FTP client, cloud provider, abandoned fork, or vendor-specific utility. Rows prioritize named, discoverable options with a first-party page, repository, vendor documentation, or App Store listing.",
    directCompetitorDefinition:
      "A Mac app that can browse shared Android storage and transfer files without first uploading them to third-party cloud storage.",
    methodology: [
      "Prefer first-party product pages, official documentation, App Store listings, and upstream source repositories.",
      "Treat competitor capabilities as vendor-claimed unless independently tested; the dataset does not award speed, reliability, or universal-device claims.",
      "Compare the public v@@VERSION@@ release, not uncommitted development work or planned features.",
      "Omit pricing and OS-minimum claims because these change and were not refreshed for this publication.",
      "Use null for a capability that was not clear enough to classify from the cited source.",
    ],
    fieldSemantics: {
      category: "The option's primary job, not every feature it includes.",
      approach: "The user-facing operating model.",
      transport: "Protocols or paths used to move data.",
      openSource: "yes, no, or not-disclosed; not-disclosed is not proof of closed source.",
      phoneApp:
        "none, required, optional, built-in, or device-vendor. ADB authorization is tracked separately.",
      debugging:
        "none, required, or optional. Required means Android developer options / USB debugging are part of the normal path.",
      account: "none, optional, or required for the described transfer path.",
      cloud:
        "none, optional, required, or server-assisted. Server-assisted can include signaling or relay infrastructure even when payloads are usually peer-to-peer.",
      twoWay: "Whether the described path supports both Mac-to-phone and phone-to-Mac transfer.",
      liveBrowse:
        "Whether the Mac can navigate device-visible folders rather than only send selected files, sync a replica, or restore a backup.",
      finderMount:
        "Whether the option claims to expose Android-managed storage through Finder; a standalone dual-pane browser is not a Finder mount.",
    },
    publishingNotes: [
      "Recheck product capabilities, release status, and Google device eligibility before publishing an updated comparison.",
      "Keep direct USB browsers separate from nearby sharing, cloud sync, migration tools, and developer workflows; they solve overlapping but different jobs.",
      "Do not describe Android File Transfer for macOS as the only free or open-source option.",
      "Do not claim that Google offers no Mac transfer path: selected 2026 Android devices can interoperate with AirDrop through Quick Share, but that is not a live folder browser.",
    ],
    relatedOptionsNotIndividuallyProfiled: [
      "OpenMTP for ARM (unofficial App Store derivative)",
      "DroidSync",
      "McDroid",
      "Phone Manager for Android",
      "MobileTrans",
      "Syncios Mobile Manager",
      "AnyDroid",
      "Resilio Sync",
      "simple-mtpfs and go-mtpfs",
      "additional cloud drives and generic LAN file-server apps",
    ],
  });

  window.MARKET_OPTIONS = Object.freeze([
    {
      id: "aft-macos",
      name: "Android File Transfer for macOS",
      category: "Direct USB browser",
      approach: "Companion-free dual-pane MTP file browser",
      transport: ["USB MTP"],
      status: "early release",
      openSource: "yes",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Browse shared Android storage and copy files or folders in either direction. v@@VERSION@@ includes Finder drag-and-drop, progress, phone rename and delete, same-name choices, and signed/notarized Apple-silicon and Intel DMGs.",
      limitations:
        "Early release. No folder move, resumable transfer, or Finder mount. Real-device testing is deepest on Samsung hardware.",
      sourceUrl:
        "https://github.com/nostitos/android-file-transfer-for-macos/releases/latest",
    },
    {
      id: "openmtp",
      name: "OpenMTP",
      category: "Direct USB browser",
      approach: "Standalone dual-pane MTP file browser",
      transport: ["USB MTP"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "MIT-licensed MTP browser with internal/SD-card storage access, files over 4 GB, drag-and-drop, grid/list modes, keyboard shortcuts, and Apple-silicon support.",
      limitations:
        "Uses its own browser rather than mounting the phone as a normal Finder volume. Published performance figures are project claims, not cross-product benchmarks.",
      sourceUrl: "https://github.com/ganeshrvel/openmtp",
    },
    {
      id: "macdroid",
      name: "MacDroid",
      category: "Finder integration",
      approach: "Mount Android storage in Finder",
      transport: ["USB MTP", "USB ADB", "Wi-Fi"],
      status: "current",
      openSource: "no",
      phoneApp: "none",
      debugging: "optional",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: true,
      summary:
        "Commercial utility that exposes Android storage through Finder and offers MTP, ADB, and wireless connection modes, including internal and SD-card storage.",
      limitations:
        "Bidirectional transfer and editing may depend on the selected plan. ADB mode requires developer settings even though MTP does not.",
      sourceUrl: "https://www.macdroid.app/",
    },
    {
      id: "commander-one",
      name: "Commander One",
      category: "Direct USB browser",
      approach: "Android access inside a commercial dual-pane file manager",
      transport: ["USB MTP"],
      status: "current",
      openSource: "no",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "optional",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "A general dual-pane Mac file manager whose PRO feature set includes Android MTP browsing and transfer alongside archive, preview, remote-server, and cloud tools.",
      limitations:
        "Android integration is part of a broader file-manager product, and it does not present the device as a Finder volume.",
      sourceUrl: "https://commander-one.com/android-file-transfer/",
    },
    {
      id: "smoothdroid",
      name: "SmoothDroid",
      category: "Direct USB browser",
      approach: "Polished standalone MTP file manager",
      transport: ["USB MTP"],
      status: "current",
      openSource: "no",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Signed and notarized commercial MTP browser with two-way transfer, previews, drag-and-drop, folder operations, and both Intel and Apple-silicon support.",
      limitations:
        "It remains a separate browser rather than a Finder mount; consult the vendor for current transfer limits.",
      sourceUrl: "https://smoothdroid.app/",
    },
    {
      id: "droidmac",
      name: "DroidMac",
      category: "Direct USB browser",
      approach: "Native MTP browser with optional wireless companion path",
      transport: ["USB MTP", "Wi-Fi companion"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "optional",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Free native Mac app that combines companion-free USB MTP browsing with an optional Android companion for Wi-Fi and send-to-device workflows.",
      limitations:
        "Wireless features change the otherwise companion-free setup model. Check the vendor's current architecture and OS requirements.",
      sourceUrl: "https://www.droidmac.com/",
    },
    {
      id: "mactransfer",
      name: "MacTransfer",
      category: "ADB / companion browser",
      approach: "Native file manager using a phone companion and ADB-style connection",
      transport: ["USB", "Wi-Fi"],
      status: "current",
      openSource: "no",
      phoneApp: "required",
      debugging: "optional",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Native Intel/Apple-silicon app for USB or Wi-Fi browsing and transfer, positioned as a faster ADB-based alternative to MTP.",
      limitations:
        "Requires a different phone-side/setup model from plain MTP; consult the vendor for current transfer limits.",
      sourceUrl: "https://mactransfer.app/",
    },
    {
      id: "idroid",
      name: "iDroid — Explorer for Android",
      category: "Direct USB browser",
      approach: "Native browser spanning MTP and ADB modes",
      transport: ["USB MTP", "USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "optional",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "App Store file manager with wired MTP, wired/wireless ADB, internal/SD-card access, multi-device support, drag-and-drop, and phone-side file operations.",
      limitations:
        "Some capabilities depend on ADB and therefore developer settings. Source availability is not stated as clearly as open-source projects.",
      sourceUrl:
        "https://apps.apple.com/us/app/idroid-explorer-for-android/id6746444380?mt=12",
    },
    {
      id: "phone-mechanic",
      name: "Phone Mechanic (for Android)",
      category: "Finder integration",
      approach: "Expose Android MTP storage directly in Finder",
      transport: ["USB MTP"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: true,
      summary:
        "App Store utility that mounts Android MTP content in Finder for native browsing, preview, drag-and-drop, and file management.",
      limitations:
        "Finder mounting is a deeper integration surface than a standalone browser and can carry different compatibility tradeoffs.",
      sourceUrl:
        "https://apps.apple.com/us/app/phone-mechanic-for-android/id1599486428?mt=12",
    },
    {
      id: "mtptransfer",
      name: "MTPtransfer",
      category: "Direct USB browser",
      approach: "Small native SwiftUI MTP browser",
      transport: ["USB MTP"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Native App Store utility for offline MTP browsing, drag-and-drop, upload/download, and common create, rename, and delete operations.",
      limitations:
        "Has a shorter public track record than established alternatives. Check the current App Store compatibility listing.",
      sourceUrl:
        "https://apps.apple.com/in/app/mtptransfer/id6760402084?mt=12",
    },
    {
      id: "mtp-file-transfer-store",
      name: "MTP File Transfer",
      category: "Direct USB browser",
      approach: "Native read/browse/export MTP utility",
      transport: ["USB MTP"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: false,
      liveBrowse: true,
      finderMount: false,
      summary:
        "App Store utility for browsing Android phones, cameras, and other MTP devices with metadata and Quick Look; check the current listing for export terms.",
      limitations:
        "Oriented to device-to-Mac browsing/export rather than full bidirectional management. Check the current App Store compatibility listing.",
      sourceUrl:
        "https://apps.apple.com/us/app/mtp-file-transfer/id6763582190?mt=12",
    },
    {
      id: "usb-phone-transfer",
      name: "USB Phone Transfer",
      category: "Direct USB browser",
      approach: "Paid dual-pane MTP transfer utility",
      transport: ["USB MTP"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "App Store MTP app for browsing phone folders and copying files in either direction without cloud storage.",
      limitations:
        "Requires a very recent macOS release. The listing had limited public history and contained unfinished-looking privacy copy at the research date, so claims need hands-on validation.",
      sourceUrl:
        "https://apps.apple.com/us/app/usb-phone-transfer/id6762877133?mt=12",
    },
    {
      id: "qfast",
      name: "QFast — Android File Transfer",
      category: "ADB / companion browser",
      approach: "Mac browser paired with a required QFast Link Android app",
      transport: ["USB", "Wi-Fi companion"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Free App Store file browser that pairs with the vendor's QFast Link Android app to browse and transfer over cable or local wireless connection.",
      limitations:
        "Requires installing a companion outside the plain USB-MTP workflow. Its trust, update, and compatibility model therefore spans both Mac and Android packages.",
      sourceUrl:
        "https://apps.apple.com/us/app/qfast-android-file-transfer/id6766607312?mt=12",
    },
    {
      id: "findroid",
      name: "Findroid",
      category: "ADB / companion browser",
      approach: "Native browser paired with a required Android companion",
      transport: ["USB", "Local Wi-Fi companion"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Native Mac file manager that uses a dedicated Android companion to find, browse, transfer, and manage phone files.",
      limitations:
        "Requires a companion app, so it is not a no-install phone path. Check current OS requirements with the vendor.",
      sourceUrl: "https://apps.apple.com/us/app/findroid/id6763690353?mt=12",
    },
    {
      id: "macmtp",
      name: "MacMTP",
      category: "Direct USB browser",
      approach: "Native SwiftUI dual-pane browser built on a Go MTP core",
      transport: ["USB MTP"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "MIT-licensed native app with list/icon views, transfer progress, pause/resume, conflict choices, and device-side MTP operations on Intel and Apple silicon.",
      limitations:
        "Its published roadmap called out MTP-to-Finder drag as unfinished at the research date. Check current OS requirements with the project.",
      sourceUrl: "https://github.com/kalabhaftu/MacMTP",
    },
    {
      id: "swiftmtp-neighbor-z",
      name: "SwiftMTP (Neighbor-Z)",
      category: "Direct USB browser",
      approach: "Native Swift MTP browser with optional AI metadata tools",
      transport: ["USB MTP", "Optional AI API"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "none",
      account: "optional",
      cloud: "optional",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "GPL-licensed native MTP app with browsing, Quick Look, two-way transfer, device-side file operations, drag-and-drop, localization, a CLI, and optional natural-language/AI analysis tools.",
      limitations:
        "AI mode is optional but can send filenames, types, dates, device model, and USB state to a configured API provider; the project's privacy page says file contents are not sent.",
      sourceUrl: "https://github.com/Neighbor-Z/SwiftMTP",
    },
    {
      id: "swiftmtp-wang93wei",
      name: "SwiftMTP (wang93wei)",
      category: "Direct USB browser",
      approach: "Source-available native Swift/Kalam MTP browser",
      transport: ["USB MTP"],
      status: "source-only",
      openSource: "yes",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "MIT-licensed Swift/Kalam project advertising multilingual MTP browsing and upload/download, including files larger than 4 GB.",
      limitations:
        "Did not provide the same ready-to-install release channel or maturity signals as established apps at the research date. Check current OS requirements with the project.",
      sourceUrl: "https://github.com/wang93wei/SwiftMTP",
    },
    {
      id: "whoozle-aft",
      name: "android-file-transfer-linux (whoozle)",
      category: "Developer MTP tool",
      approach: "Cross-platform CLI/FUSE and library tooling",
      transport: ["USB MTP", "FUSE"],
      status: "current-source",
      openSource: "yes",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: null,
      summary:
        "LGPL cross-platform MTP implementation with command-line, library, and filesystem-oriented components that can be built on macOS.",
      limitations:
        "Primarily a developer/source project rather than a signed, notarized, consumer Mac download; setup and macOS filesystem integration require technical work.",
      sourceUrl: "https://github.com/whoozle/android-file-transfer-linux",
    },
    {
      id: "webmtp",
      name: "WebMTP",
      category: "Developer MTP tool",
      approach: "Browser-based MTP experiment using WebUSB",
      transport: ["USB WebUSB/MTP"],
      status: "prototype",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: null,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Experimental WebUSB implementation showing that an MTP browser can run as a web app in a compatible browser.",
      limitations:
        "Prototype with no stable consumer releases and no apparent license declaration at the research date; WebUSB browser support and USB permissions are material constraints.",
      sourceUrl: "https://github.com/Brooksolomon/webmtp",
    },
    {
      id: "google-aft-legacy",
      name: "Google Android File Transfer (legacy)",
      category: "Legacy / unavailable",
      approach: "Former standalone Google MTP browser",
      transport: ["USB MTP"],
      status: "legacy-de-listed",
      openSource: "no",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "The old Google utility many users still search for; its former Mac download page no longer provides the MTP application and now routes toward Quick Share information.",
      limitations:
        "Not presented or documented through Google's current transfer guidance. Treat the historical installer as legacy search context, not as a formally discontinued or currently supported recommendation.",
      sourceUrl: "https://www.android.com/filetransfer/",
    },
    {
      id: "android-file-sync",
      name: "AndroidFileSync",
      category: "ADB / developer",
      approach: "Native SwiftUI ADB file manager and sync utility",
      transport: ["USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "required",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "GPL native ADB manager with Quick Look, collision handling, batch operations, trash/restore, app management, wireless connections, and multi-device support.",
      limitations:
        "Requires Android developer options and debugging authorization. Manual installation currently documents a Gatekeeper quarantine workaround rather than a fully notarized consumer flow.",
      sourceUrl: "https://github.com/Santosh7017/AndroidFileSync",
    },
    {
      id: "droiddock",
      name: "DroidDock",
      category: "ADB / developer",
      approach: "Tauri desktop ADB browser with search and sync preview",
      transport: ["USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "required",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "MIT-licensed ADB browser with thumbnails/previews, recursive search, multi-view navigation, hidden-file support, deletion, and folder-sync preview.",
      limitations:
        "Requires developer mode/USB debugging and upstream builds are not positioned as fully signed/notarized consumer downloads; Gatekeeper workarounds may be necessary.",
      sourceUrl: "https://github.com/rajivm1991/DroidDock",
    },
    {
      id: "androidbridge",
      name: "AndroidBridge",
      category: "ADB / developer",
      approach: "Native Swift ADB browser",
      transport: ["USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "required",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "MIT native app supporting wired/wireless ADB browsing, previews, multiselect, file/folder transfer, progress, and cancellation.",
      limitations:
        "Requires external Android platform tools and debugging authorization. Published builds were ad-hoc signed rather than a standard notarized distribution at the research date.",
      sourceUrl: "https://github.com/togiwan/AndroidBridge",
    },
    {
      id: "axchange",
      name: "Axchange",
      category: "ADB / developer",
      approach: "Paid native ADB file manager",
      transport: ["USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "required",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Native App Store ADB file manager with preview, drag-and-drop, create, rename, move, copy, and delete operations.",
      limitations:
        "Developer options and debugging authorization are required; this is a different audience and security/setup tradeoff from plug-in MTP.",
      sourceUrl:
        "https://apps.apple.com/us/app/axchange-adb-file-transfer/id6737504944?mt=12",
    },
    {
      id: "andromeld",
      name: "AndroMeld",
      category: "ADB / phone integration suite",
      approach: "Finder mount plus Android app mirroring and continuity features",
      transport: ["USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "not-disclosed",
      phoneApp: "none",
      debugging: "required",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: true,
      summary:
        "Broad Android integration suite claiming Finder file management, Quick Look, app mirroring, notifications, clipboard sync, APK inspection, and wired/wireless ADB support.",
      limitations:
        "Far broader than a basic transfer utility, and requires a recent macOS and ADB setup.",
      sourceUrl:
        "https://apps.apple.com/us/app/andromeld-android-companion/id6762439757?mt=12",
    },
    {
      id: "adb-cli",
      name: "Android Debug Bridge (adb)",
      category: "ADB / developer",
      approach: "Official command-line push/pull and device shell",
      transport: ["USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "required",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Google's official platform tool can push or pull arbitrary files and directories and script repeatable USB or wireless transfers.",
      limitations:
        "Command-line workflow with developer options, per-computer authorization, and Android permission boundaries; not a discoverable consumer file browser.",
      sourceUrl: "https://developer.android.com/tools/adb",
    },
    {
      id: "android-studio-device-explorer",
      name: "Android Studio Device Explorer",
      category: "ADB / developer",
      approach: "Official IDE-integrated device filesystem explorer",
      transport: ["USB ADB", "Wi-Fi ADB"],
      status: "current",
      openSource: "yes",
      phoneApp: "none",
      debugging: "required",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Android Studio's GUI for viewing, copying, uploading, synchronizing, and deleting files on an ADB-connected device or emulator.",
      limitations:
        "Requires the full Android development environment and debugging authorization; app-private data access is constrained on non-debuggable production apps.",
      sourceUrl:
        "https://developer.android.com/studio/debug/device-file-explorer",
    },
    {
      id: "android-drop-quick-share-airdrop",
      name: "Android Drop: Quick Share ↔ AirDrop",
      category: "Nearby sharing",
      approach: "Send selected items between supported Android phones and AirDrop",
      transport: ["Quick Share", "AirDrop", "Local wireless", "Optional QR cloud relay"],
      status: "selected-devices",
      openSource: "no",
      phoneApp: "built-in",
      debugging: "none",
      account: "optional",
      cloud: "optional",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Google's 2026 interoperability path lets selected Android phones exchange chosen items with nearby Macs through AirDrop-style discovery and confirmation.",
      limitations:
        "Limited to an evolving selected-device list and send/receive workflow, not browsing phone folders. Unsupported devices can use a QR fallback that uploads encrypted files to Google servers temporarily and has limits.",
      sourceUrl:
        "https://blog.google/products-and-platforms/platforms/android/android-drop-june-2026/",
    },
    {
      id: "localsend",
      name: "LocalSend",
      category: "Nearby sharing",
      approach: "Cross-platform local-network send/receive app",
      transport: ["LAN HTTPS"],
      status: "current",
      openSource: "yes",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Apache-licensed cross-platform AirDrop-style sharing over the local network with HTTPS, no account, and no third-party cloud storage.",
      limitations:
        "Requires LocalSend on both devices and the same reachable network; it sends selected files/folders rather than exposing Android storage for live browsing.",
      sourceUrl: "https://localsend.org/",
    },
    {
      id: "kde-connect",
      name: "KDE Connect",
      category: "Nearby sharing",
      approach: "Cross-platform phone/computer continuity suite",
      transport: ["LAN TLS"],
      status: "current",
      openSource: "yes",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Open-source local-network suite for files, clipboard, notifications, remote input, and other cross-device functions.",
      limitations:
        "Requires KDE Connect on both devices and network pairing. File sharing is one feature in a broad suite and is not the same as an MTP folder browser.",
      sourceUrl: "https://kdeconnect.kde.org/",
    },
    {
      id: "neardrop",
      name: "NearDrop",
      category: "Nearby sharing",
      approach: "Unofficial Quick Share receiver for macOS",
      transport: ["Quick Share", "Local Wi-Fi"],
      status: "current",
      openSource: "yes",
      phoneApp: "built-in",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: false,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Open-source partial Quick Share implementation that lets a Mac receive files sent from nearby Android devices on the same local network.",
      limitations:
        "Receive-only, unofficial, partial protocol support, same-network requirement, and upstream distribution is not signed/notarized like a conventional consumer app.",
      sourceUrl: "https://github.com/grishka/NearDrop",
    },
    {
      id: "pairdrop",
      name: "PairDrop",
      category: "Nearby sharing",
      approach: "Browser/PWA peer-to-peer sharing",
      transport: ["WebRTC", "WebSocket signaling", "Optional TURN relay"],
      status: "current",
      openSource: "yes",
      phoneApp: "optional",
      debugging: "none",
      account: "none",
      cloud: "server-assisted",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "GPL browser-based sharing that discovers peers and transfers selected files through WebRTC, with PWA and self-hosting options.",
      limitations:
        "Requires browser sessions and signaling infrastructure; relays may be involved when direct peer connectivity fails. No remote folder browser.",
      sourceUrl: "https://github.com/schlagmichdoch/PairDrop",
    },
    {
      id: "feem",
      name: "Feem",
      category: "Nearby sharing",
      approach: "Proprietary cross-platform LAN transfer app",
      transport: ["LAN", "TLS 1.3"],
      status: "current",
      openSource: "no",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Cross-platform companion apps transfer selected files over the local network without routing payloads through cloud storage.",
      limitations:
        "Requires Feem on both devices and local-network connectivity; there is no live phone-storage browser.",
      sourceUrl: "https://feem.io/en",
    },
    {
      id: "send-anywhere",
      name: "Send Anywhere",
      category: "Nearby / internet sharing",
      approach: "Key, link, or device-based cross-platform sending",
      transport: ["Direct transfer", "Internet relay/storage"],
      status: "current",
      openSource: "no",
      phoneApp: "required",
      debugging: "none",
      account: "optional",
      cloud: "optional",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Cross-platform selected-file transfer using short keys, device targeting, or share links, with direct and server-mediated modes.",
      limitations:
        "A transfer service rather than a storage browser; privacy, retention, limits, and network path vary by mode and plan.",
      sourceUrl: "https://send-anywhere.com/en/download",
    },
    {
      id: "bluetooth-file-exchange",
      name: "macOS Bluetooth File Exchange",
      category: "Built-in macOS",
      approach: "Send or receive individual files over Bluetooth OBEX",
      transport: ["Bluetooth OBEX"],
      status: "current-built-in",
      openSource: "no",
      phoneApp: "built-in",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Apple's built-in Bluetooth utility can exchange selected files with compatible paired devices without Wi-Fi, cloud storage, or a USB cable.",
      limitations:
        "Slow for large transfers, device/OBEX behavior varies, and it offers send/receive dialogs rather than live Android storage browsing.",
      sourceUrl:
        "https://support.apple.com/guide/mac-help/share-files-mac-bluetooth-devices-mchle7fa9e15/mac",
    },
    {
      id: "airdroid-personal",
      name: "AirDroid Personal",
      category: "Phone integration suite",
      approach: "Account-based companion suite for remote and local management",
      transport: ["LAN", "Internet", "USB for selected features"],
      status: "current",
      openSource: "no",
      phoneApp: "required",
      debugging: "optional",
      account: "required",
      cloud: "optional",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Large phone-management suite with file transfer, remote access/control, screen mirroring, notifications, messaging, and web access.",
      limitations:
        "Requires an AirDroid phone app and account for the normal experience; remote/cloud services differ from an offline USB utility.",
      sourceUrl: "https://www.airdroid.com/personal/",
    },
    {
      id: "syncmate",
      name: "SyncMate",
      category: "Sync / backup",
      approach: "Scheduled Mac/Android data synchronization",
      transport: ["USB", "Wi-Fi", "Bluetooth"],
      status: "current",
      openSource: "no",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "optional",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Commercial synchronization tool for folders and personal data across Android, Mac, cloud accounts, and other services.",
      limitations:
        "Optimized for configured synchronization jobs rather than ad-hoc live browsing.",
      sourceUrl: "https://www.sync-mac.com/",
    },
    {
      id: "drfone-phone-manager",
      name: "Dr.Fone Phone Manager",
      category: "Phone integration suite",
      approach: "Commercial media and phone-data manager",
      transport: ["USB", "Wi-Fi for selected workflows"],
      status: "current",
      openSource: "no",
      phoneApp: "optional",
      debugging: "optional",
      account: "optional",
      cloud: "optional",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Commercial suite for transferring and organizing photos, music, video, contacts, messages, apps, and other phone data.",
      limitations:
        "Much broader, heavier, and more expensive than a basic shared-storage browser; workflows, supported data types, and licensing vary by module and device.",
      sourceUrl: "https://drfone.wondershare.com/android-transfer.html",
    },
    {
      id: "droidkit",
      name: "DroidKit",
      category: "Phone integration suite",
      approach: "Commercial Android data manager, recovery, and repair suite",
      transport: ["USB", "Device helper workflows"],
      status: "current",
      openSource: "no",
      phoneApp: "optional",
      debugging: "optional",
      account: "optional",
      cloud: "optional",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Commercial suite spanning Android data management, migration, extraction, recovery, unlocking, and system repair.",
      limitations:
        "The product's scope and permissions extend far beyond file transfer. Device-specific support needs separate review.",
      sourceUrl: "https://www.imobie.com/droidkit/android-data-manager.htm",
    },
    {
      id: "samsung-smart-switch",
      name: "Samsung Smart Switch",
      category: "OEM migration / backup",
      approach: "Samsung backup, restore, and phone migration",
      transport: ["USB", "Wi-Fi for device migration"],
      status: "current",
      openSource: "no",
      phoneApp: "device-vendor",
      debugging: "none",
      account: "none",
      cloud: "optional",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Samsung's official utility for backing up a Galaxy device to a Mac, restoring it, updating software, and migrating to another phone.",
      limitations:
        "Samsung-specific and organized around backups/migration rather than freely browsing shared storage. Not a general Android file manager.",
      sourceUrl:
        "https://www.samsung.com/uk/support/mobile-devices/how-do-i-backup-my-smartphone-to-my-pc-or-mac/",
    },
    {
      id: "huawei-hisuite",
      name: "Huawei HiSuite",
      category: "OEM migration / backup",
      approach: "Huawei device management and backup suite",
      transport: ["USB", "Wi-Fi for selected functions"],
      status: "current",
      openSource: "no",
      phoneApp: "device-vendor",
      debugging: "none",
      account: "optional",
      cloud: "optional",
      twoWay: true,
      liveBrowse: true,
      finderMount: false,
      summary:
        "Huawei's desktop suite for device data, backup/restore, updates, and selected file-management tasks.",
      limitations:
        "Huawei-specific, may require enabling HDB and a phone-side service, and is a broad device-management suite rather than universal MTP browsing.",
      sourceUrl: "https://consumer.huawei.com/en/support/hisuite/",
    },
    {
      id: "image-capture",
      name: "macOS Image Capture",
      category: "Built-in macOS",
      approach: "Import photos and videos from camera/PTP devices",
      transport: ["USB PTP", "Camera import protocols"],
      status: "current-built-in",
      openSource: "no",
      phoneApp: "none",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: false,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Apple's built-in importer can retrieve photos and videos when an Android device exposes a compatible camera/PTP interface.",
      limitations:
        "Media-import workflow only: no arbitrary shared-storage browsing, no Mac-to-phone upload, and device USB mode/support varies.",
      sourceUrl:
        "https://support.apple.com/guide/image-capture/image-capture-user-guide-imgcp1003/mac",
    },
    {
      id: "cloud-drives",
      name: "Cloud drives (Drive, Dropbox, OneDrive)",
      category: "Cloud transfer / sync",
      approach: "Upload on one device, download or sync on the other",
      transport: ["Internet", "Provider cloud storage"],
      status: "current",
      openSource: "no",
      phoneApp: "required",
      debugging: "none",
      account: "required",
      cloud: "required",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Ubiquitous cross-device path: upload files from Android to a provider and access them from the Mac browser or sync client, and vice versa.",
      limitations:
        "Uses third-party storage, an account, internet bandwidth, and storage quotas; it syncs provider folders rather than browsing the phone's live filesystem.",
      sourceUrl: "https://www.google.com/drive/",
    },
    {
      id: "syncthing",
      name: "Syncthing ecosystem",
      category: "Sync / backup",
      approach: "Peer-to-peer replication of chosen folders",
      transport: ["LAN", "Internet peer-to-peer", "Optional discovery/relay"],
      status: "current-core-android-client-transition",
      openSource: "yes",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "server-assisted",
      twoWay: true,
      liveBrowse: false,
      finderMount: false,
      summary:
        "Open-source continuous folder replication between devices without a central file-storage account; discovery and relay services can assist connectivity.",
      limitations:
        "A synchronization system, not an ad-hoc phone browser. The official Android app repository is archived, so users must assess maintained Android client options separately.",
      sourceUrl: "https://syncthing.net/",
    },
    {
      id: "phone-file-server",
      name: "Phone-hosted FTP / HTTP / WebDAV / SMB",
      category: "LAN file server",
      approach: "Run a server app on Android and connect from Finder or a browser/client",
      transport: ["LAN FTP", "HTTP", "WebDAV", "SMB"],
      status: "current-generic-workflow",
      openSource: "not-disclosed",
      phoneApp: "required",
      debugging: "none",
      account: "none",
      cloud: "none",
      twoWay: true,
      liveBrowse: true,
      finderMount: true,
      summary:
        "A generic local-network pattern: an Android app serves chosen storage over a standard protocol and the Mac connects through Finder, a browser, or a dedicated client.",
      limitations:
        "Requires installing, configuring, starting, and securing a phone server; protocol support, write access, permissions, encryption, and sleep behavior vary by app.",
      sourceUrl:
        "https://support.apple.com/guide/mac-help/connect-your-mac-to-shared-computers-and-servers-mchlp1140/mac",
    },
  ]);
})();
